version: '3'
services:
  app:
    container_name: app-server
    image: owncloud/server
    stdin_open: true
    tty: true
    restart: always
    expose:
      - '80'
      - '8080'
    networks:
      - onlyoffice
    volumes:
      - ./onlyoffice:/tmp/onlyoffice
      - ./run.sh:/run.sh
    command: bash /run.sh
  onlyoffice-document-server:
    container_name: onlyoffice-document-server
    image: onlyoffice/documentserver:latest
    stdin_open: true
    tty: true
    restart: always
    networks:
      - onlyoffice
    expose:
      - '80'
      - '443'
    volumes:
      - document_data:/var/www/onlyoffice/Data
      - document_log:/var/log/onlyoffice
  nginx:
    container_name: nginx-server
    image: nginx
    stdin_open: true
    tty: true
    restart: always
    ports:
      - 80:80
      - 443:443
    networks:
      - onlyoffice
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
networks:
  onlyoffice:
    driver: 'bridge'
volumes:
  document_data:
  document_log:
  mysql_data:
